config/routes.rb
HotCompress::Application.routes.draw do
	
devise_for :users

resources :url_pairs

match 'url_pairs_list_all' => 'url_pairs#list_all'
match 'url_pairs_graph' => 'url_pairs#graph'

root :to => "url_pairs#index"

  

  
  match '*a', :to => redirect {|params, r| 
	puts params
	u = UrlPair.find_by_short_url(params[:a])
	u.hit_count += 1
	u.save
	
	u.long_url.to_s 
	
	}
end
 

app/models/url_pair.rb
class UrlPair < ActiveRecord::Base
  attr_accessible :long_url, :short_url, :user_id
  
  validates_presence_of :short_url
  validates_uniqueness_of :short_url, :case_sensitive => true#
  validates_presence_of :long_url
  validates_presence_of :user_id
  validates_presence_of :hit_count
  
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
		 :token_authenticatable, :confirmable,
		 :lockable, :timeoutable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body
  
  has_many :url_pairs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery
	
	def not_found
		#raise ActionController::RoutingError.new('Not Found')
		render :text => '404 Error - Not Found', :status => 404
	end
	
	def current_or_guest_user
		if current_user
			if session[:guest_user_id]
				logging_in
				guest_user.destroy
				session[:guest_user_id] = nil
			end
			@current_user = current_user
			@uid = current_user.id
			@guest_user = nil
		else
			@guest_user = guest_user
			@uid = guest_user.id		
		end
		puts "user id is #{@uid}"
	end
	
	# find guest_user object associated with the current session,
	# creating one as needed
	def guest_user
		guest_user = User.find_by_email("guest@e.com")
		if ( guest_user.nil? )
			guest_user = create_guest_user
		end
		guest_user
		#User.find(session[:guest_user_id].nil? ? session[:guest_user_id] = create_guest_user.id : session[:guest_user_id])
	end
	
	private

	# called (once) when the user logs in, insert any code your application needs
	# to hand off from guest_user to current_user.	
	def logging_in
		# For example:
		# guest_comments = guest_user.comments.all
		# guest_comments.each do |comment|
			# comment.user_id = current_user.id
			# comment.save
		# end
	end
	
	def create_guest_user
		puts "attempting to create guest user"
		u = User.create(:name => "guest", :email => "guest@e.com", password: "Gibberish")
		#u = User.create(:name => "guest", :email => "guest_#{Time.now.to_i}#{rand(99)}@example.com")
		u.skip_confirmation!
		#u.save(:validate => false) #dangerous, don't use
		u
	end
	
end

app/controllers/url_pairs_controller.rb
class UrlPairsController < ApplicationController

  before_filter :get_url_pair, :only => [ :edit, :show, :update, :destroy ]
  def get_url_pair
    begin
      @url_pair = UrlPair.find(params[:id]) 
    rescue
      not_found
    end
    uid
  end


  def uid
    if @guest_user
      @uid = guest_user.id
    else
      if current_user.nil?
        @uid = User.find_by_email("guest@e.com")
      else 
        @uid = current_user.id
      end
    end
  end

  def index
    current_or_guest_user
    @url_pairs = User.find_by_id(@uid).url_pairs.all
    @url_pairs.sort_by! { |s| s[:short_url]}
    @host = request.host
    @port = request.port
    puts "domain: #{@host}:#{@port}"
    if @uid == guest_user.id
      puts "Logged in as guest"
    else
      puts "Logged in as #{current_user.email}"
    end
  end

  def show
    #uid
    #@url_pair = UrlPair.find(params[:id])
  end

  def new
    uid
    @rand = false
    @url_pair = UrlPair.new
    @url_pair.long_url = "http://"
    @url_pair.short_url = SecureRandom.urlsafe_base64(2)
    #@url_pair.short_url = 'y'
    #UrlPair.all do |u| puts "test #{u.include?(@url_pair.short_url)}" end
    #UrlPair.all do |u| puts "test" end
  end

  def create
    current_or_guest_user
    @url_pair = UrlPair.new(params[:url_pair])
    @url_pair.user_id = @uid
    @url_pair.hit_count = 0
    if @url_pair.save
      redirect_to @url_pair, notice: "Url pair was successfully created" 
    else
      render action: "new"
    end
  end 

  def edit
    #uid
    #@url_pair = UrlPair.find(params[:id])
  end

  def update
    #@url_pair = UrlPair.find(params[:id])
    #uid
    @url_pair.user_id = @uid
    if @url_pair.hit_count.nil? || @url_pair.hit_count <= 0
      @url_pair.hit_count = 0
    end
    if @url_pair.update_attributes(params[:url_pair])
      redirect_to(@url_pair, :notice => "Url pair was successfully updated")
    else
      render "edit"
    end
  end

  def destroy
    #@url_pair = UrlPair.find(params[:id])
    @url_pair.delete
    redirect_to url_pairs_url
  end

  def list_all
    current_or_guest_user
    @url_pairs = UrlPair.find(:all, :order => 'hit_count DESC')
    puts @url_pairs
    #@url_pairs.sort_by { |, hit_count| 
  end

  def graph
    current_or_guest_user
    @url_pairs = UrlPair.find(:all, :order => 'hit_count DESC')
    @urlp = @url_pairs.map do |u| u.hit_count end
    @h = LazyHighCharts::HighChart.new('graph') do |f|
      f.options[:chart][:defaultSeriesType] = "bar"
      f.options[:title][:text] = "Url Pair Hit Counts"
      f.options[:yAxis][:alternateGridColor] = '#FDFFD5'
      #f.tooltip[:formatter][:function] = "Short Url is @{this.x}"
      @urlc = @url_pairs.map do |u| "#{u.long_url} : #{u.short_url}" end
      f.xAxis(:categories=>@urlc)
      f.series(:name=>'URL Pairs', :data=>@urlp )
    end
  end
end

app/helpers/url_pair_helper.rb
module UrlPairHelper
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
    %a.close{"data-dismiss" => "alert"} &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.haml
= link_to " Hot Compress", root_path, :class => 'brand'
%ul.nav
  %li
    = link_to "Create New Pair", new_url_pair_path
  - if user_signed_in?
    %li
      = link_to('Logout', destroy_user_session_path, :method=>'delete')
  - else
    %li
      = link_to('Login', new_user_session_path)
  - if user_signed_in?
    %li
      = link_to('Edit account', edit_user_registration_path)
  - else
    %li
      = link_to('Sign up', new_user_registration_path)
  %li
    = link_to "List All", url_pairs_list_all_path
  %li
    = link_to "Graph", url_pairs_graph_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Hot Compress"
    %meta{:content => "", :name => "URL shortener"}
    %meta{:content => "", :name => "Eric Lindow"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = javascript_include_tag :high_charts
    = csrf_meta_tags
    = yield(:head)
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container-fluid
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container-fluid
        .content
          .row
            .span8
              = render 'layouts/messages'
              = yield
          %footer

app/views/shared/_error_msg.html.haml
- if model.errors.any?
	.error_explanation
		%h3= "#{pluralize(model.errors.count,'error')} saving #{model.class}:"
		%ul
			- model.errors.full_messages.each do |msg|
				%li= msg

app/views/url_pairs/_form.html.haml
=simple_form_for @url_pair, :html => {:class => 'form-vertical'} do |f|
	= render 'shared/error_msg', model: @url_pair
	= f.input :long_url, :as => :string, :label => 'The long url you want to go to:', :label_html => { :class => nil }
	= f.input :short_url, :as => :string, :label => '   The short url you will enter:'
	= "Owner: #{User.find_by_id(@uid).name}"
	= f.button :submit, :class => "btn primary", :class => 'btn btn-custom'

app/views/url_pairs/_form1.html.haml
- if @guest_user
	Using this site as Guest, id=#{@guest_user.id}
	= #link_to 'Login', new_user_session_path
- else
	Logged in as #{current_user.name}, id=#{current_user.id}
	= #link_to 'End Session', destroy_user_session_path, :confirm => "Are you sure?", :method => :delete
	= #link_to 'Edit Profile', edit_user_registration_path

app/views/url_pairs/edit.html.haml
%h2= "Edit this pair of URL's (long and/or short):"

= render 'form1'

= render 'form'

= link_to 'Back', url_pairs_path

app/views/url_pairs/graph.html.haml
%h2 Url Pairs Graph
= render 'form1'
=" -  URL Pair Count: #{UrlPair.count}"	

= high_chart("Url Pairs", @h)

%br
= link_to "Back", url_pairs_path, :class => 'btn btn-mini'

app/views/url_pairs/index.html.haml
%h2 Listing of Url Pairs

= render 'form1'

=" - #{User.find_by_id(@uid).name}'s URL Pair Count: #{@url_pairs.count}"

%table
	%tr
		%th= "Long URL"
		%th= "Short" 
		%th= "Owner"
		%th= "Hits"
	-	@url_pairs.each do |url_pair|
		%tr
			%td= url_pair.long_url
			%td= link_to "#{url_pair.short_url}", url_pair.short_url
			%td= url_pair.user.name
			%td= url_pair.hit_count
			%td= #link_to 'Test', url_pair.short_url
			%td= link_to 'Show', url_pair_path(url_pair), :class => 'btn btn-mini'
			%td= link_to 'Edit', edit_url_pair_path(url_pair), {:class => 'btn btn-mini'} 
			%td= link_to 'Destroy', url_pair, :confirm => "Are you sure?", :method => :delete, :class => 'btn btn-mini'
%br			
= link_to "Create New Url Pair", new_url_pair_path, :class => 'btn btn-custom'

app/views/url_pairs/list_all.html.haml
%h3 Listing of All Url Pairs by Number of Hits
%br
= render 'form1'

="-  Total URL Pair Count: #{UrlPair.count}"

%table
	%tr
		%th= "Long URL"
		%th= "Short" 
		%th= "Owner"
		%th= "Hits"
	-	@url_pairs.each do |url_pair|
		%tr
			%td= url_pair.long_url
			%td= link_to "#{url_pair.short_url}", url_pair.short_url
			%td= url_pair.user.name
			%td= url_pair.hit_count
%br			
= link_to "Back", url_pairs_path, :class => 'btn btn-mini'

	

app/views/url_pairs/new.html.haml
%h2 Enter a new pair of URLs

= render 'form'

= link_to 'Back', url_pairs_path(@url_pair), :class => 'btn btn-mini'

app/views/url_pairs/show.html.haml
%h2 #{@url_pair.short_url} #{@url_pair.long_url}

%ul
	%li= "Long Url: #{@url_pair.long_url}"
	%li= "Short Url: #{@url_pair.short_url}"
	%li= "Owner: #{@url_pair.user.email}"
	
= link_to 'Edit', edit_url_pair_path(@url_pair)
|
= link_to 'Back', url_pairs_path

app/views/url_pairs/update.html.haml
%h1 UrlPair#update
%p Find me in app/views/url_pair/update.html.haml